### ISSUE TITLE
Fails on linux

### ISSUE THREAD

**Issue by 0x00A** [dominictarr/noderify#13]
The command...
```
noderify --electron src/index.js > bundle.js
```
works fine on osx but fails on `linux (Mint, Ubuntu)` node `6.3.0` with the following error...

```
Error: Cannot find module 'electron' from '/home/test/work/voltraco/voltra/src'
    at /usr/lib/node_modules/noderify/bin.js:3645:17
    at process (/usr/lib/node_modules/noderify/bin.js:3772:43)
    at ondir (/usr/lib/node_modules/noderify/bin.js:3787:17)
    at load (/usr/lib/node_modules/noderify/bin.js:3668:43)
    at onex (/usr/lib/node_modules/noderify/bin.js:3691:31)
    at /usr/lib/node_modules/noderify/bin.js:3621:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by 0x00A** [comment]
lol, just realized... have you ever used this with electron? You are [`missing the electron module`](https://github.com/dominictarr/noderify/blob/master/index.js#L23-L29) 🎱 😄

**Comment by 0x00A** [comment]
so, FYI, version 1.1.0 works fine on osx and linux, but 2.0.0 seems to fail in many ways. Most notably, `src/node_modules/foo.js` can not successfully `require('bar')`. The issue i noted above is probably pretty big too.

**Comment by dominictarr** [comment]
oh, that needs updating for electron@1, electron@0 didn't have an `electron` module yet

**Comment by 0x00A** [comment]
that fixes the first issue, which i patched locally and fixed, but the second problem seemed much more involved.

**Comment by dominictarr** [comment]
can you make a script that reproduces this?

**Comment by dominictarr** [comment]
today I have been working on creating browser bundles that run the same in both browser and electron.
and I realized that `browserify --no-builtins --igv ,` does what this module was trying to do. seems to work.
that comma is not a typo. `igv` is short for `insert-global-variables` and it's a comma separated list. `,` is the only way to say an empty list.

The only thing is it will use the `"browser": {...}` options in the package.json. that may not be what you want, but it might work. also, I think relative requires of native addons won't work, but absolute ones will.

This was enough for my use case.  https://github.com/dominictarr/browselectrify

**Comment by 0x00A** [comment]
ah! this is excellent. i think this can be closed then?

**Comment by 0x00A** [comment]
hmm, it doesnt seem to work for me...
```
$ browserify --no-builtins --igv , ./src/index.js > bundle.js
Error: Cannot find module 'electron' from '/Users/u/src'
```

(I get the same error from browselectrify).

**Comment by dominictarr** [comment]
oh, try adding `--exclude electron` hmm, maybe that should be part of browselectrify
